// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"backend/internal/handlers"
	"backend/internal/services"
	"backend/internal/storages"
)

// Injectors from wire.go:

func InitUserHandler() *handlers.TaskHandler {
	iTaskStorage := storages.NewTaskStorage()
	iTaskService := services.NewTaskService(iTaskStorage)
	taskHandler := handlers.NewTaskHandler(iTaskService)
	return taskHandler
}
